dist: xenial
language: java
jdk: openjdk15
install: true
addons:
  sonarcloud:
    organization: $SONAR_ORGANIZATION
    token: $SONAR_TOKEN
script:
  - mvn clean package sonar:sonar -P sonar
cache:
  directories:
    - $HOME/.m2
    - $home/.sonar/cache
